require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false